server:
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    max-connections: 900
    min-spare-threads: 100
    accesslog:
      enabled: true
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b %T'
      directory: ${user.dir}/logs
      prefix: access.${HOST:127.0.0.1}.${server.port:8080}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3306/feedback?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC"
    username: root
    password: 123456
    dbcp2:
      initial-size: 20
      max-total: 50
      max-idle: 10
      max-wait-millis: 5000
      min-idle: 5
      test-on-borrow: true
      validation-query: SELECT 1
      time-between-eviction-runs-millis: 300000
      num-tests-per-eviction-run: 20
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        search:
          default:
            directory_provider: org.hibernate.search.store.impl.FSDirectoryProvider
            indexBase: E:/index

logging:
  file: ${user.dir}/logs/process.${HOST:127.0.0.1}.${server.port:8080}
